version: 2
jobs:
  build:
    parallelism: 3
    working_directory: /app
    docker:
      - image: circleci/buildpack-deps:18.04-browsers
        user: root
    steps:
      - checkout
      # Remove OpenJDK 11 from CircleCI base images, in favor of default JDK
      # version from distro.
      - run: apt-get -y purge openjdk-11-jre openjdk-11-jre-headless openjdk-11-jdk openjdk-11-jdk-headless
      # Install any system package dependencies.
      - run: env INSTALL_TEST_DEPENDENCIES=true ./tasks/install-system-build-dependencies
      - restore_cache:
          # CircleCI's prefix based matching will mean the cache from the last
          # cache for this branch will be restored.
          key: cache-build-deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-
      # The bootstrap's "task" file will be cached on subsequent runs, but due
      # to the reliance on timestamps, this fact might not get picked up in the
      # CI environment. So if a stamp file exists for the initial bootstrap
      # process, re-touch it to prevent re-downloads.
      - run: touch -c build/work/stamp/bootstrap-*
      # Build all the API Umbrella software dependencies.
      - run: ./configure
      - run: make all test-deps
      - run: make clean:dev
      # Cache the staged build data and task checksums of what's been
      # completed.
      - save_cache:
          key: cache-build-deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-{{ epoch }}
          paths:
            - .task
            - build/work/dev-env
            - build/work/stage
            - build/work/stamp
            - build/work/task
            - build/work/tasks
            - build/work/test-env
      - run: groupadd -r api-umbrella && useradd -r -g api-umbrella -s /sbin/nologin -d /opt/api-umbrella -c "API Umbrella user" api-umbrella
      - run: make test:circle-ci
      - store_test_results:
          path: test/tmp/reports
      - store_artifacts:
          path: test/tmp/run/api-umbrella-root/var/log
      - store_artifacts:
          path: test/tmp/capybara
