apiUmbrella:
  mongodb: "mongodb://127.0.0.1:27017/api_umbrella_development"
  redis:
    host: 127.0.0.1
    port: 6379
  elasticsearch:
    hosts:
      - host: 127.0.0.1
        port: 9200
  accountSignupUri: "http://example.com/"
  contactUri: "http://example.com/contact"
  trustedProxies:
    - 127.0.0.1
  proxy:
    workers: 1
    host: 0.0.0.0
    port: 7890
    target: "127.0.0.1:6081"
    apiKeyMethods:
      - header
      - getParam
      - basicAuthUsername
    rateLimits:
      - duration: 1000
        accuracy: 500
        limitBy: ip
        limit: 50
        distributed: false
      - duration: 1000
        accuracy: 500
        limitBy: apiKey
        limit: 20
        distributed: false
      - duration: 15000
        accuracy: 1000
        limitBy: ip
        limit: 250
        distributed: true
      - duration: 15000
        accuracy: 1000
        limitBy: apiKey
        limit: 150
        distributed: true
      - duration: 3600000
        accuracy: 60000
        limitBy: apiKey
        limit: 1000
        distributed: true
        responseHeaders: true
    restrictedApis: []
  logProcessor:
    workers: 1
  routerLogListener:
    workers: 1
    logPath: log/router.log
