app_env: production
services:
  - general_db
  - log_db
  - router
  - web
user: api-umbrella
group: api-umbrella
rlimits:
  nofile: 100000
  nproc: 20000
http_port: 80
https_port: 443
nginx:
  workers: auto
  worker_connections: 8192
  access_log_filename: access.log
  access_log_options: buffer=256k flush=10s
  proxy_connect_timeout: 60
  proxy_read_timeout: 60
  proxy_send_timeout: 60
  keepalive_timeout: 75
  ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"
  ssl_ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
  ssl_session_cache: "shared:ssl_sessions:50m"
  ssl_session_timeout: 24h
  ssl_session_tickets: "off"
  ssl_buffer_size: 1400
  ssl_prefer_server_ciphers: "on"
  ssl_ecdh_curve: secp384r1
  lua_ssl_trusted_certificate:
  lua_ssl_verify_depth: 1
  dyups:
    host: 127.0.0.1
    port: 14005
  shared_dicts:
    active_config:
      size: 3m
    api_users:
      size: 3m
    dns_cache:
      size: 300k
    geocode_city_cache:
      size: 100k
    interval_locks:
      size: 20k
    locks:
      size: 20k
    resolved_hosts:
      size: 100k
    stats:
      size: 20m
    upstream_checksums:
      size: 200k
  _reloader_frequency: 14400 # 4 hours
gatekeeper:
  api_key_methods:
    - header
    - getParam
    - basicAuthUsername
  api_key_cache: true
  idp_providers:
    - fiware-oauth2
    - github-oauth2
    - facebook-oauth2
    - google-oauth2
  default_idp:
    backend_name: fiware-oauth2
    host: http://idm.docker:8000
trafficserver:
  host: 127.0.0.1
  port: 14009
  autoconf_port: 14007
  management_port: 14008
  storage:
    size: 256M
  embedded_server_config:
    records: []
api_server:
  host: 127.0.0.1
  port: 14010
web:
  host: 127.0.0.1
  port: 14012
  rails_secret_token:
  request_timeout: 30
  puma:
    workers: 2
    min_threads: 2
    max_threads: 24
  api_user:
    first_name_exclude_regex: "(http|https|www|<|>|\\r|\\n)"
    last_name_exclude_regex: "(http|https|www|<|>|\\r|\\n)"
  admin:
    initial_superusers: []
    username_is_email: true
    password_length_min: 14
    password_length_max: 72
    email_regex: "\\A[^@\\s]+@[^@\\s]+\\z"
    password_regex:
    auth_strategies:
      enabled:
        - local
      cas:
        options: {}
      facebook:
        client_id:
        client_secret:
      github:
        client_id:
        client_secret:
      gitlab:
        client_id:
        client_secret:
      google:
        client_id:
        client_secret:
      ldap:
        options: {}
      max.gov:
        require_mfa: true
  mailer:
    smtp_settings:
static_site:
  host: 127.0.0.1
  port: 14013
router:
  api_backends:
    host: 127.0.0.1
    port: 14011
    keepalive_connections: 10
  trusted_proxies: []
  global_rate_limits:
    ip_rate:
    ip_burst:
    ip_rate_size: 8m
    ip_rate_log_level: error
    ip_connections:
    ip_connections_size: 5m
    ip_connections_log_level: error
  web_app_host: "*"
  web_app_backend_regex: "^/(admin|admins|web-assets)(/|$)"
  web_app_backend_required_https_regex: "^.*"
  website_backend_required_https_regex_default: "^.*"
  redirect_not_found_to_https: true
rsyslog:
  host: 127.0.0.1
  port: 14014
dns_resolver:
  negative_ttl: 60
  max_stale: 86400
  timeout: 2000
  retries: 3
mongodb:
  url: "mongodb://127.0.0.1:14001/api_umbrella"
  read_preference: primaryPreferred
  embedded_server_config:
    processManagement:
      fork: false
    net:
      bindIp: 127.0.0.1
      port: 14001
mora:
  host: 127.0.0.1
  port: 14004
  timeout: 0
elasticsearch:
  hosts:
    - "http://127.0.0.1:14002"
  embedded_server_env:
    heap_size: 512m
  api_version: 2
  embedded_server_config:
    network:
      host: 127.0.0.1
    http:
      port: 14002
    transport:
      tcp:
        port: 14003
    cluster:
      name: api-umbrella
    indices:
      fielddata:
        cache:
          size: 40%
      breaker:
        fielddata:
          limit: 60%
    index:
      translog:
        # Sync the data to disk asynchronously on a fixed interval, rather than
        # for every request. This significantly helps indexing throughput (at
        # the risk of losing a few seconds of data if things crash).
        durability: async
        sync_interval: 10s
analytics:
  adapter: elasticsearch
  timezone: UTC
  log_request_url_query_params_separately: false
kylin:
  protocol: http
  host: 127.0.0.1
  port: 7070
presto:
  protocol: http
  host: 127.0.0.1
  port: 14015
  embedded_server_config:
    http_port: 14015
    max_memory: 2GB
    max_memory_per_node: 1GB
    discovery_uri: http://127.0.0.1:14015
    query_max_run_time: 60s
    hive:
      metastore_uri: thrift://127.0.0.1:9083
flume:
  host: 127.0.0.1
  port: 14016
  embedded_server_config:
    java_opts:
kafka:
  brokers: []
  topic: api_umbrella_logs
log_template_version: v1
strip_cookies:
  - ^__utm.*$
  - ^_ga$
  - ^is_returning$
site_name: API Umbrella
apiSettings:
  require_https: required_return_error
  rate_limits:
    - duration: 1000
      accuracy: 500
      limit_by: ip
      limit: 50
      distributed: false
    - duration: 1000
      accuracy: 500
      limit_by: apiKey
      limit: 20
      distributed: false
    - duration: 15000
      accuracy: 1000
      limit_by: ip
      limit: 250
      distributed: true
    - duration: 15000
      accuracy: 1000
      limit_by: apiKey
      limit: 150
      distributed: true
    - duration: 3600000
      accuracy: 60000
      limit_by: apiKey
      limit: 1000
      distributed: true
      response_headers: true
  error_templates:
    json: |-
      {
        "error": {
          "code": {{code}},
          "message": {{message}}
        }
      }
    xml: |-
      <?xml version="1.0" encoding="UTF-8"?>
      <response>
        <error>
          <code>{{code}}</code>
          <message>{{message}}</message>
        </error>
      </response>
    csv: |-
      Error Code,Error Message
      {{code}},{{message}}
    html: |-
      <html>
        <body>
          <h1>{{code}}</h1>
          <p>{{message}}</p>
        </body>
      </html>
  error_data:
    common:
      signup_url: "{{base_url}}"
      contact_url: "{{base_url}}/contact/"
    not_found:
      status_code: 404
      code: NOT_FOUND
      message: The requested URL was not found on this server.
    api_key_missing:
      status_code: 403
      code: API_KEY_OR_TOKEN_MISSING
      message: No api_key or token was supplied. Get one at {{signup_url}}
    api_key_invalid:
      status_code: 403
      code: API_KEY_OR_TOKEN_INVALID
      message: An invalid api_key or token was supplied. Get one at {{signup_url}}
    api_key_disabled:
      status_code: 403
      code: API_KEY_DISABLED
      message: The api_key supplied has been disabled. Contact us at {{contact_url}} for assistance
    api_key_unverified:
      status_code: 403
      code: API_KEY_UNVERIFIED
      message: The api_key supplied has not been verified yet. Please check your e-mail to verify the API key. Contact us at {{contact_url}} for assistance
    api_key_unauthorized:
      status_code: 403
      code: API_KEY_OR_TOKEN_UNAUTHORIZED
      message: The api_key or token supplied is not authorized to access the given service. Contact us at {{contact_url}} for assistance
    token_not_supported:
      status_code: 403
      code: TOKEN_NOT_SUPPORTED
      message: The accessed API do not support authorization based on a token issued by an external identity provider, use your API key instead
    over_rate_limit:
      status_code: 429
      code: OVER_RATE_LIMIT
      message: You have exceeded your rate limit. Try again later or contact us at {{contact_url}} for assistance
    internal_server_error:
      status_code: 500
      code: INTERNAL_SERVER_ERROR
      message: An unexpected error has occurred. Try again later or contact us at {{contact_url}} for assistance
    https_required:
      status_code: 400
      code: HTTPS_REQUIRED
      message: "Requests must be made over HTTPS. Try accessing the API at: {{https_url}}"
internal_apis:
  - _id: api-umbrella-gatekeeper-backend
    name: API Umbrella - Gatekeeper APIs
    frontend_host: "{{router.web_app_host}}"
    backend_host: 127.0.0.1
    backend_protocol: http
    balance_algorithm: least_conn
    sort_order: 1
    servers:
      - host: "{{api_server.host}}"
        port: "{{api_server.port}}"
    url_matches:
      - frontend_prefix: "/api-umbrella/v1/health"
        backend_prefix: "/api-umbrella/v1/health"
      - frontend_prefix: "/api-umbrella/v1/state"
        backend_prefix: "/api-umbrella/v1/state"
    sub_settings:
      - http_method: get
        regex: "^/api-umbrella/v1/(health|state)"
        settings:
          disable_api_key: true
          rate_limit_mode: unlimited
          require_https: optional
  - _id: api-umbrella-web-backend
    name: API Umbrella - Web APIs
    frontend_host: "{{router.web_app_host}}"
    backend_host: 127.0.0.1
    backend_protocol: http
    balance_algorithm: least_conn
    sort_order: 1
    servers:
      - host: "{{web.host}}"
        port: "{{web.port}}"
    url_matches:
      - frontend_prefix: "/api-umbrella/"
        backend_prefix: "/api-umbrella/"
    sub_settings:
      - http_method: post
        regex: "^/api-umbrella/v1/users"
      - http_method: post
        regex: "^/api-umbrella/v1/contact"
internal_website_backends:
  - _id: api-umbrella-website-backend
    frontend_host: "{{router.web_app_host}}"
    backend_protocol: http
    server_host: "{{static_site.host}}"
    server_port: "{{static_site.port}}"
ban:
  user_agents:
  ips:
  response:
    status_code: 403
    delay: 0
    message: "Please contact us for assistance."
ember_server:
  port: 14050
  live_reload_port: 14051
