app_env: production
services:
  - general_db
  - log_db
  - router
  - web
user: api-umbrella
group: api-umbrella
rlimits:
  nofile: 100000
  nproc: 20000
http_port: 80
https_port: 443
listen:
  addresses:
    - "*"
    - "[::]"
nginx:
  workers: auto
  worker_connections: 8192
  listen_so_keepalive: "on"
  listen_backlog:
  error_log_level: notice
  access_log_filename: access.log
  access_log_options: buffer=256k flush=10s
  proxy_connect_timeout: 30
  proxy_read_timeout: 60
  proxy_send_timeout: 60
  proxy_buffer_size: 8k
  proxy_buffers: 8 8k
  keepalive_timeout: 75
  ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"
  ssl_ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
  ssl_session_cache: "shared:ssl_sessions:50m"
  ssl_session_timeout: 24h
  ssl_session_tickets: "off"
  ssl_buffer_size: 1400
  ssl_prefer_server_ciphers: "on"
  ssl_ecdh_curve: secp384r1
  lua_ssl_trusted_certificate:
  lua_ssl_verify_depth: 1
  shared_dicts:
    active_config:
      size: 3m
    api_users:
      size: 3m
    geocode_city_cache:
      size: 100k
    interval_locks:
      size: 20k
    locks:
      size: 20k
    stats:
      size: 20m
    upstream_checksums:
      size: 200k
    discovery:
      size: 200k
    jwks:
      size: 200k
    introspection:
      size: 200k
  vhost_traffic_status:
    enabled: false
    filter_by_host: "on"
gatekeeper:
  api_key_methods:
    - header
    - getParam
    - basicAuthUsername
  api_key_cache: true
trafficserver:
  host: 127.0.0.1
  port: 14009
  storage:
    size: 256M
  embedded_server_config:
    records: []
api_server:
  host: 127.0.0.1
  port: 14010
web:
  host: 127.0.0.1
  port: 14012
  request_timeout: 30
  workers: 2
  worker_connections: 8192
  listen_so_keepalive: "on"
  listen_backlog:
  error_log_level: notice
  api_user:
    email_regex: "\\A[^@\\s]+@[^@\\s]+\\.[^@\\s]+\\z"
    first_name_exclude_regex: "(http|https|www|<|>|\\r|\\n)"
    last_name_exclude_regex: "(http|https|www|<|>|\\r|\\n)"
  admin:
    initial_superusers: []
    username_is_email: true
    password_length_min: 14
    password_length_max: 72
    email_regex: "\\A[^@\\s]+@[^@\\s]+\\.[^@\\s]+\\z"
    password_regex:
    auth_strategies:
      enabled:
        - local
      cas:
        options:
          service_validate_url: /serviceValidate
          login_url: /login
          logout_url: /logout
          ssl: true
      facebook:
        client_id:
        client_secret:
      github:
        client_id:
        client_secret:
      gitlab:
        client_id:
        client_secret:
        discovery: https://gitlab.com/.well-known/openid-configuration
        token_signing_alg_values_expected: RS256
        token_endpoint_auth_method: client_secret_post
        scope: openid email
      google:
        client_id:
        client_secret:
        discovery: https://accounts.google.com/.well-known/openid-configuration
        token_signing_alg_values_expected: RS256
        token_endpoint_auth_method: client_secret_post
        scope: openid email
        authorization_params:
          prompt: select_account
      ldap:
        options:
          port: 389
          method: plain
          uid: sAMAccountName
      login.gov:
        client_id:
        client_rsa_private_key:
        discovery: https://idp.int.identitysandbox.gov/.well-known/openid-configuration
        token_signing_alg_values_expected: RS256
        token_endpoint_auth_method: private_key_jwt
        scope: openid email
        authorization_params:
          acr_values: http://idmanagement.gov/ns/assurance/loa/1
      max.gov:
        require_mfa: true
        options:
          host: login.max.gov
          login_url: /cas/login
          service_validate_url: /cas/serviceValidate
          logout_url: /cas/logout
          ssl: true
  contact:
    email_regex: "\\A[^@\\s]+@[^@\\s]+\\.[^@\\s]+\\z"
    name_exclude_regex: "(http|https|www|<|>|\\r|\\n)"
    api_exclude_regex: "(<script|\\r|\\n)"
    subject_exclude_regex: "(<script|\\r|\\n)"
    message_exclude_regex: "(\\A\\s*\\d+\\s*\\z)"
  mailer:
    smtp_settings:
      address: 127.0.0.1
      port: 25
  analytics_v0_summary_required_role: api-umbrella-public-metrics
  analytics_v0_summary_start_time: 2013-07-01T00:00:00.000Z
  analytics_v0_summary_end_time:
  analytics_v0_summary_filter:
  max_body_size: 1m
static_site:
  host: 127.0.0.1
  port: 14013
router:
  api_backends:
    keepalive_connections: 20
    keepalive_idle_timeout: 120
  trusted_proxies: []
  global_rate_limits:
    ip_rate:
    ip_burst:
    ip_rate_size: 8m
    ip_rate_log_level: error
    ip_connections:
    ip_connections_size: 5m
    ip_connections_log_level: error
  web_app_host: "*"
  website_backend_required_https_regex_default: "^.*"
  redirect_not_found_to_https: true
auto_ssl:
  workers: 1
  worker_connections: 8192
  listen_so_keepalive: "on"
  listen_backlog:
  http:
    port: 14005
  https:
    port: 14006
  user: api-umbrella-auto-ssl
  group: api-umbrella-auto-ssl
  hook_server:
    port: 14007
rsyslog:
  host: 127.0.0.1
  port: 14014
log:
  destination: file
dns_resolver:
  negative_ttl: 60
  max_stale: 86400
  timeout: 2000
  retries: 3
  # This default could be revisited, but historically we didn't resolve AAAA
  # records for API backends, so for compatibility keep this disabled by
  # default. Enabling may also break certain hosting environments that still
  # aren't IPv6 compatible.
  allow_ipv6: false
postgresql:
  host: 127.0.0.1
  port: 14011
  database: api_umbrella
  username: api_umbrella_app
  password:
  ssl: false
  ssl_verify:
  ssl_required:
  migrations:
    username: api_umbrella_owner
    password:
  auto_ssl:
    username: api_umbrella_auto_ssl
    password:
  embedded_server_config:
    listen_addresses: 127.0.0.1
    port: 14011
mongodb:
  url: "mongodb://127.0.0.1:14001/api_umbrella"
  read_preference: primaryPreferred
  embedded_server_config:
    processManagement:
      fork: false
    net:
      bindIp: 127.0.0.1
      port: 14001
mora:
  host: 127.0.0.1
  port: 14004
  timeout: 0
elasticsearch:
  hosts:
    - "http://127.0.0.1:14002"
  embedded_server_env:
    heap_size: 512m
  index_name_prefix: api-umbrella
  index_partition: monthly
  index_mapping_type: log
  api_version: 2
  template_version: 1
  embedded_server_config:
    network:
      host: 127.0.0.1
    http:
      port: 14002
    transport:
      tcp:
        port: 14003
    cluster:
      name: api-umbrella
    indices:
      fielddata:
        cache:
          size: 40%
      breaker:
        fielddata:
          limit: 60%
  aws_signing_proxy:
    host: 127.0.0.1
    port: 14017
    workers: 1
    worker_connections: 8192
    listen_so_keepalive: "on"
    listen_backlog:
    error_log_level: notice
analytics:
  adapter: elasticsearch
  timezone: UTC
  log_request_url_query_params_separately: false
strip_cookies:
  - ^__utm.*$
  - ^_ga$
  - ^is_returning$
strip_response_cookies: []
strip_server_header: false
site_name: API Umbrella
apiSettings:
  require_https: required_return_error
  rate_limits:
    - duration: 1000
      accuracy: 500
      limit_by: ip
      limit_to: 50
      distributed: false
    - duration: 1000
      accuracy: 500
      limit_by: apiKey
      limit_to: 20
      distributed: false
    - duration: 15000
      accuracy: 1000
      limit_by: ip
      limit_to: 250
      distributed: true
    - duration: 15000
      accuracy: 1000
      limit_by: apiKey
      limit_to: 150
      distributed: true
    - duration: 3600000
      accuracy: 60000
      limit_by: apiKey
      limit_to: 1000
      distributed: true
      response_headers: true
  error_templates:
    json: |-
      {
        "error": {
          "code": {{code}},
          "message": {{message}}
        }
      }
    xml: |-
      <?xml version="1.0" encoding="UTF-8"?>
      <response>
        <error>
          <code>{{code}}</code>
          <message>{{message}}</message>
        </error>
      </response>
    csv: |-
      Error Code,Error Message
      {{code}},{{message}}
    html: |-
      <html>
        <body>
          <h1>{{code}}</h1>
          <p>{{message}}</p>
        </body>
      </html>
  error_data:
    common:
      signup_url: "{{base_url}}"
      contact_url: "{{base_url}}/contact/"
    not_found:
      status_code: 404
      code: NOT_FOUND
      message: The requested URL was not found on this server.
    api_key_missing:
      status_code: 403
      code: API_KEY_MISSING
      message: No api_key was supplied. Get one at {{signup_url}}
    api_key_invalid:
      status_code: 403
      code: API_KEY_INVALID
      message: An invalid api_key was supplied. Get one at {{signup_url}}
    api_key_disabled:
      status_code: 403
      code: API_KEY_DISABLED
      message: The api_key supplied has been disabled. Contact us at {{contact_url}} for assistance
    api_key_unverified:
      status_code: 403
      code: API_KEY_UNVERIFIED
      message: The api_key supplied has not been verified yet. Please check your e-mail to verify the API key. Contact us at {{contact_url}} for assistance
    api_key_unauthorized:
      status_code: 403
      code: API_KEY_UNAUTHORIZED
      message: The api_key supplied is not authorized to access the given service. Contact us at {{contact_url}} for assistance
    over_rate_limit:
      status_code: 429
      code: OVER_RATE_LIMIT
      message: You have exceeded your rate limit. Try again later or contact us at {{contact_url}} for assistance
    internal_server_error:
      status_code: 500
      code: INTERNAL_SERVER_ERROR
      message: An unexpected error has occurred. Try again later or contact us at {{contact_url}} for assistance
    https_required:
      status_code: 400
      code: HTTPS_REQUIRED
      message: "Requests must be made over HTTPS. Try accessing the API at: {{https_url}}"
internal_apis:
  - id: api-umbrella-gatekeeper-backend
    name: API Umbrella - Gatekeeper APIs
    frontend_host: "{{router.web_app_host}}"
    backend_host: ~
    backend_protocol: http
    balance_algorithm: least_conn
    sort_order: 1
    servers:
      - host: "{{api_server.host}}"
        port: "{{api_server.port}}"
    url_matches:
      - frontend_prefix: "/api-umbrella/v1/health"
        backend_prefix: "/api-umbrella/v1/health"
      - frontend_prefix: "/api-umbrella/v1/state"
        backend_prefix: "/api-umbrella/v1/state"
      - frontend_prefix: "/api-umbrella/v0/nginx-status"
        backend_prefix: "/api-umbrella/v0/nginx-status"
      - frontend_prefix: "/api-umbrella/v0/shared-memory-stats"
        backend_prefix: "/api-umbrella/v0/shared-memory-stats"
    settings:
      require_https: required_return_error
    sub_settings:
      - http_method: get
        regex: "^/api-umbrella/v1/(health|state)"
        settings:
          disable_api_key: true
          rate_limit_mode: unlimited
          require_https: optional
          disable_analytics: true
  - id: api-umbrella-web-app-backend
    name: API Umbrella - HTTP APIs
    frontend_host: "{{router.web_app_host}}"
    backend_host: ~
    backend_protocol: http
    balance_algorithm: least_conn
    sort_order: 2
    servers:
      - host: "{{web.host}}"
        port: "{{web.port}}"
    url_matches:
      - frontend_prefix: "/api-umbrella/"
        backend_prefix: "/api-umbrella/"
      - frontend_prefix: "/admins/"
        backend_prefix: "/admins/"
      - frontend_prefix: "/admins"
        backend_prefix: "/admins"
        exact_match: true
      - frontend_prefix: "/admin/"
        backend_prefix: "/admin/"
      - frontend_prefix: "/admin"
        backend_prefix: "/admin"
        exact_match: true
      - frontend_prefix: "/web-assets/"
        backend_prefix: "/web-assets/"
    settings:
      require_https: required_return_error
    sub_settings:
      - http_method: any
        regex: "^/admin/stats"
        settings:
          disable_api_key: true
      - http_method: POST
        regex: "^/admin/login"
        settings:
          disable_api_key: true
          rate_limit_mode: custom
          rate_limits:
            - duration: 15000
              accuracy: 1000
              limit_by: ip
              limit_to: 100
              distributed: true
              response_headers: true
      - http_method: any
        regex: "^/(admin|web-assets)"
        settings:
          disable_api_key: true
          rate_limit_mode: unlimited
          redirect_https: true
          disable_analytics: true
      - http_method: OPTIONS
        regex: "^/api-umbrella/v1/users"
        settings:
          disable_api_key: true
internal_website_backends:
  - id: api-umbrella-website-backend
    frontend_host: "{{router.web_app_host}}"
    backend_protocol: http
    server_host: "{{static_site.host}}"
    server_port: "{{static_site.port}}"
ban:
  user_agents:
  ips:
  response:
    status_code: 403
    delay: 0
    message: "Please contact us for assistance."
ember_server:
  port: 14050
  live_reload_port: 14051
umask: "0027"
geoip:
  db_update_frequency: 86400 # 24 hours
  db_update_age: 79200 # 22 hours
  maxmind_license_key:
_test_config:
  default_null_override_hash:
  default_null_override_string:
  default_empty_hash_override_hash: {}
