# Use ERB to include the contents of our shared YAML database config file.
<%= IO.read("/etc/db_config/database.yml") %>

development:
  <<: *gsa_developer_mongodb_development

test:
  <<: *gsa_developer_mongodb_test

staging_int:
  <<: *gsa_developer_mongodb_staging_int

production:
  <<: *gsa_developer_mongodb_production
