app_env: test
user:
group:
http_port: 9080
https_port: 9081
analytics:
  timezone: America/Denver
static_site:
  port: 13013
nginx:
  # We default the number of workers to the number of CPU cores, but keep this
  # hard-coded for test purposes so we have a more stable baseline and ensure
  # our tests always run with multiple workers.
  workers: 2
  # Disable log output buffering for immediate output in tests.
  access_log_options:
  # Increase error log verbosity in tests.
  error_log_level: notice
  proxy_connect_timeout: 2
  proxy_read_timeout: 5
  proxy_send_timeout: 9
trafficserver:
  port: 13009
api_server:
  port: 13010
web:
  port: 13012
  admin:
    auth_strategies:
      facebook:
        client_id: test_fake_id
        client_secret: test_fake_secret
      github:
        client_id: test_fake_id
        client_secret: test_fake_secret
      gitlab:
        client_id: test_fake_id
        client_secret: test_fake_secret
      google:
        client_id: test_fake_id
        client_secret: test_fake_secret
      ldap:
        options:
          host: 127.0.0.1
          port: 389
          method: plain
          base: dc=example,dc=com
          uid: sAMAccountName
  mailer:
    smtp_settings:
      address: 127.0.0.1
      port: 13102
  contact_form_email: default-test-contact-email@example.com
  analytics_v0_summary_start_time: 2013-07-01T00:00:00.000-06:00
  analytics_v0_summary_end_time: 2013-08-31T23:59:59.999-06:00
router:
  trusted_proxies:
    - 192.168.12.0/23
    - 10.10.10.10
rsyslog:
  port: 13014
postgresql:
  port: 13006
  database: api_umbrella_test
  embedded_server_config:
    port: 13006
mongodb:
  url: "mongodb://127.0.0.1:13001/api_umbrella_test"
  embedded_server_config:
    net:
      port: 13001
    storage:
      journal:
        enabled: false
mora:
  port: 13004
elasticsearch:
  hosts:
    - "http://127.0.0.1:13002"
  embedded_server_config:
    http:
      port: 13002
    transport:
      tcp:
        port: 13003
unbound:
  port: 13100
  control_port: 13101
mailhog:
  bind_addr: "127.0.0.1"
  smtp_port: 13102
  api_port: 13103
  ui_port: 13103
openldap:
  port: 13104
apiSettings:
  require_https: optional
_test_config:
  default_null_override_hash:
    foo: bar
  default_null_override_string: foobar
  default_empty_hash_override_hash:
    baz: qux
apis:
  - id: 00000000-0000-0000-0000-100000000000
    name: default-test-api-backend
    backend_protocol: http
    balance_algorithm: least_conn
    frontend_host: 127.0.0.1
    backend_host: 127.0.0.1
    servers:
      - id: 00000000-0000-0000-0000-200000000000
        host: 127.0.0.1
        port: 9444
    url_matches:
      - id: 00000000-0000-0000-0000-300000000000
        frontend_prefix: /api/
        backend_prefix: /
